### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Mariobai** [lzc1/Relation_extraction#1]
你这个具体的实现怎么实现的啊？用了哪些算法？过程是什么样的？

**Comment by xingyuezhiji** [comment]
同问 这个主要实现的是什么呀

**Comment by lzc1** [comment]
简单说一下：我这个项目当时是尝试进行金融领域实体关系抽取做的一些工作，包括初期对整个流程的探索。
具体实现流程：首先通过爬虫技术获得金融语料；
然后人工标注语料；
对语料进行一系列处理，分词等；
然后使用词频或者是TD-IDF值将非数值型特征转为数值型特征；
进行特征提取；
选择合适的分类算法，进行特征选择，调参等；
最后根据调差的结果，选择最佳分类算法。
文本分类。
